//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingListviewWithMetro_FrameworkandEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriId { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public Nullable<decimal> MusteriBakiye { get; set; }
        public Nullable<byte> MusteriPuan { get; set; }
    }
}
