//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerInformation
    {
        public int PerId { get; set; }
        public string PerAd { get; set; }
        public string PerSoyad { get; set; }
        public string PerSehir { get; set; }
        public Nullable<int> PerMaas { get; set; }
        public Nullable<bool> PerDurum { get; set; }
        public string PerYas { get; set; }
    }
}
